services:
  - type: web
    name: sistema-lorena
    runtime: python
    plan: free
    rootDir: webapp
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
